### ISSUE TITLE
You are breaking Cleverbot's terms of use

### ISSUE THREAD

**Issue by paulexistor** [IntriguingTiles/cleverbot-free#21]
Hello,
The reason you keep having to fix your code and put a message which says "Please use the official Cleverbot API as the Cleverbot developers can easily break this package at any time." - is because we are trying to break your package. You are hacking into an internal communication method between our website and servers. Our servers cost a lot to run so we need the revenue from people visiting the site and clicking the ads, or registering and paying for the official Cleverbot API. We kindly request that you disable this Github project. We will also contact Github and ask them to disable the project.
Thank you,
Paul (Existor Ltd)

**Comment by IntriguingTiles** [comment]
I'm sorry but that isn't going to happen. This isn't hacking unless you consider the users of your site to also be hacking. You broke the site for legitimate Chrome users on a certain version which I can't imagine is helping the revenue situation. I seriously doubt that GitHub cares whatsoever and if they do I can always switch to GitLab. I'm enjoying the cat and mouse game and I'm interested in seeing what you guys come up with next. Try not to break the site for users next time.

**Comment by paulexistor** [comment]
You're right - I've re-enabled that user agent. Though it was a very specific version number and just temporary. I'm not enjoying the cat and mouse game and there's not much else I can do programmatically, and I have tons of other work to do. So I'll leave it to the owners of the company to take further if they want to. Thanks anyway, Paul

**Comment by ollora** [comment]
Hmm. You are actually doing the following things wrong, of ever-increasing seriousness:

- Contravening the Terms of our website
- Breaching our Copyright
- Causing direct, measurable costs to us in terms of serving, which we could fully justifiably reclaim from you
- Causing indirect loss to us in terms of usage of our paid official Cleverbot API... as above
- Using our name "Cleverbot", for which we hold the Trademark, and for which reason we could pursue significant damages

I don't know. but you are presumably doing this not merely for your own entertainment, but to improve your reputation and status.  You are doing so at our cost. That is not right, and cannot continue.

Cleverbot is not a free internet utility, and we are not a large corporation with deep pockets. Cleverbot costs us time and money to maintain and serve.

I ask and advise you to stop immediately, and to in turn advise all users to stop.

Rollo
Cleverbot

**Comment by CoderViki** [comment]
Hello Cleverbot,

We pay $ 10 and we can use it 10K times. This decision may be difficult for you, but I think you have to do it unlimitedly. 
Even 10 dollars is a huge amount of money for me, the economy in our country is bad.

Thank you for allowing us to use it for free for 6 months. Cleverbot.com has become even more famous for doing this. 

#AFreeCleverbotFor3MoreMonths...

**Comment by FellowCBUser** [comment]
@paulexistor @ollora

I think a lot more developers would be enticed to use the official API if it wasn't so expensive. The high price tag on the requests - especially on the larger plans - turns off many developers. Having a more affordable price plan could generate more income, as the lower prices would encourage more developers to use it and in total bring in a larger revenue. Instead of having 5 users pay $50 per month for the API, you could have 50 users paying $5 a month for the API, as it is more affordable and therefore more enticing to developers.

Since you brought up that you're not a large corporation and your main source of revenue is advertisements, I really doubt your API's pricing is scaled as well as your ad revenue in relation to users. Is the amount of money you earn from users via ads as high as how much you would earn via that same amount of users that would access Cleverbot via the API? Additionally, many developers realistically also aren't apart of large corporations where they can afford to pay such high prices for APIs.

If the 10K API requests plan would be implemented into a service that has, say 100 users, would those 100 users generate $10 worth of revenue if they visited Cleverbot via the official site, or has the pricing of the API been scaled unreasonably?

I for one would be more than happy to pay for the API, but the application where I use the Cleverbot API doesn't even make nearly that much revenue in relation to the needed API price plan, meaning that it's impossible for me to pay for the API, and you lose a potentially valuable customer, and I assume many others are in a similar position.

The reason why a free Cleverbot package exists, and the reason why so many developers use it, is not because the option merely exists, it's because many developers do not believe the API is fairly priced based on the number of requests it allows. I understand that Existor has spent plenty of time, effort, and resources into making the best quality chatbot on the Internet (which you have by the way, great job on that), but I think it would be wise for you to reconsider your price plan, maybe trial some new options, see what other APIs do for pricing such as Google, and see what you can work out to benefit both yourselves and countless developers.

**Comment by ollora** [comment]
@IntriguingTiles @CoderViki @FellowCBUser 

It is very simple. Nothing justifies theft. Not desire to use it, belief that it's good, the convenient idea that the price is too high, nor amusement, showing off, attempting to raise your profile. Even more so... not attempting to derive any kind of financial benefit ever through its usage.

Stealing is what it is. Taking something that does not belong to you. Our server's time, our time, our Copyright material, our revenue, our name.

You all need to stop.

Rollo

**Comment by GoldenretriverYT** [comment]
This has nothing to do with stealing - they might be breaching your copyright - ok - but that can easily be changed by renaming the package.

**Comment by ollora** [comment]
@IntriguingTiles @CoderViki @FellowCBUser @GoldenretriverYT

>GoldenretriverYT: This has nothing to do with stealing - they might be breaching your copyright - ok - but that can easily be changed by renaming the package.

Not just Copyright. Trademark breach is absolutely obvious... is still happening... and is much more serious. Renaming would not in any way alter the fact that it happened.

Not only using a Trademarked name to directly compete with the Trademark owner, but taking some of the owner's product to do the competing. There could not be a clearer-cut case.

Whether or not the law is capable of proving the word 'stealing', it should be, because that is 100% what it is, both morally and practically. Every single time people access an API that was clearly, statedly put there for usage of our website only, and has costs attached, they are stealing from us - indeed from me, personally. Taking from me what I have spent a significant part of my entire working life on - Cleverbot code, serving, and, most time-consuming of all, the data. My work, my income - surprisingly enough, they are not public commodities.

People may love to pretend otherwise to themselves ("hey, this is the internet" etc), but in reality everyone doing it knows perfectly well that they are stealing.

Rollo

**Comment by oxtuple** [comment]
Wish Cleverbot was free for recreational purposes. No one that's using this package has the spare money to afford the real thing.
