### ISSUE TITLE
Access to XMLHttpRequest has been blocked?

### ISSUE THREAD

**Issue by ForgoneReality** [IntriguingTiles/cleverbot-free#41]
Hi! I'm sort of a novice to programming and I keep getting this error in my React/JS program and open it up on localhost:3000

Access to XMLHttpRequest has been blocked by CORS policy No Access-Control-Allow-Origin header found

How do I fix this? I'm not really sure how and where to add said header either... Sorry for the dumb question

**Comment by IntriguingTiles** [comment]
Unfortunately, there is no way to use cleverbot-free directly in the browser because CORS, by default, prevents one site from making requests to other sites unless it has been explicitly allowed by the other site. What you could do is use cleverbot-free server-side and expose an endpoint for the browser to use.
